### ISSUE TITLE
Issues to load glb model

### ISSUE THREAD

**Issue by bimintelligence** [Twinklebear/webgpu-gltf#1]
Hi, it's a very interesting project.
I've stuck in some trouble to load my glb model, the console information is shown as below.

[ALL0112Model_0.zip](https://github.com/Twinklebear/webgpu-gltf/files/13916493/ALL0112Model_0.zip)

![image](https://github.com/Twinklebear/webgpu-gltf/assets/73410751/6b8311db-2b1b-4588-a806-b7c2461197ef)
![image](https://github.com/Twinklebear/webgpu-gltf/assets/73410751/b95e6a9e-8708-4214-bf2e-cee6e5ebface)

**Comment by Twinklebear** [comment]
Hi @SHAWNZHANGSH , to check the model is loading what you expect, you can add prints:

- Here: https://github.com/Twinklebear/webgpu-gltf/blob/main/src/glb_import.js#L721 to print out `mesh['name']`
- Here: https://github.com/Twinklebear/webgpu-gltf/blob/main/src/glb_import.js#L742 to print out `node.name` and `node.mesh.name`

This will tell you which meshes in the GLB file are being uploaded to the GPU, and which nodes in the file are being added to the scene and uploaded, and what meshes they reference. The meshes referenced by the loaded nodes are what will be rendered.

The other likely thing that can be happening (since no errors are being output) is that your model is bigger or smaller than the default camera is configured to view (see here: https://github.com/Twinklebear/webgpu-gltf/blob/main/src/glb_viewer.js#L67-L69 . The application is very simple, and does not compute the bounding box of the model to automatically position the camera so that the model is visible. You can try loading the model up in Blender and looking at its size and position, and then adjust the camera position based on that.

**Comment by bimintelligence** [comment]
Hi, thank you for your advice.
Printed logs are shown below.
These model could be visualized in the 3D viewer.

![image](https://github.com/Twinklebear/webgpu-gltf/assets/73410751/ae826996-daa3-41b1-8805-acb9af648fd3)


![image](https://github.com/Twinklebear/webgpu-gltf/assets/73410751/fa772a76-9a15-48f9-9e50-9db45aa70e2b)

The model loaded in the blender is shown like this.
![image](https://github.com/Twinklebear/webgpu-gltf/assets/73410751/88277721-d764-4ec1-990f-7dbc4ad1caab)

**Comment by Twinklebear** [comment]
It looks like the node name is undefined, you could try just printing out the `node` variable. I tried loading the initial model you sent in Blender and it just had one node (not like your screenshot there) and I didn't see anything visible after trying to re-center the model.

In your Blender pic, the model has a very large transform on X & Y. Since the glTF viewer in this repo doesn't recenter the camera on the object, that is probably why it's not visible since it's very far offscreen

**Comment by bimintelligence** [comment]
Hi, thank you for your attention.
I have identified the reasons for the issues mentioned above. 
One major factor is that the model's size is too large. 
A significant portion of it is shadows (as shown in the image below). 
However, I am not certain whether it is a result of the lighting conditions in the scene or an issue with the camera.

![image](https://github.com/Twinklebear/webgpu-gltf/assets/73410751/48d9fd1b-c07b-4fd6-8105-8163deea8f92)

**Comment by Twinklebear** [comment]
Great!

For the shadows thing: the gltf viewer implemented in this repo doesn't do lighting or shadows, what you're seeing there might be the large model being clipped off by the far clip plane if it's very large. You can check that by opening it in Blender and exploring it more, to see how that data in that region looks.
